[package]
name = "udger-rust"
version = "0.1.0"
authors = ["jack"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "udger"

[dependencies]
anyhow = "1.0"
regex = "1.3.9"
# uchardet = "2.0.4"
hyperscan = { version="0.2.0", features=["chimera"] }
getset = "0.1"

[dependencies.rusqlite]
version = "0.24.0"
features = ["bundled"]

[features]
icon = []
homepage = []
url = []
