[package]
name = "udger-rust"
version = "0.1.2"
authors = ["Jack Liar"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "udger"

[dependencies]
anyhow = "1.0"
# uchardet = "2.0.4"
clru = "0.5"
hyperscan = { version="0.2", features=["chimera"] }
lazy_static = "1.4.0"
libc = "0.2"
log = "0.4"
regex = "1.4"
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"

[dependencies.rusqlite]
version = "0.25"
features = ["bundled"]

[features]
icon = []
homepage = []
url = []
application = []
